name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_test_linux:
    name: build_test_linux
    runs-on: ubuntu-22.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: install_go
        uses: actions/setup-go@v3
        with:
          go-version: '^1.12.1'
      - name: install_dependencies
        run: |
          ls -lah
          go version
          go get github.com/protosam/go-libnss
      - name: build
        run: |
          CGO_CFLAGS="-g -O2 -D __LIB_NSS_NAME=external" go build --buildmode=c-shared -o libnss_external.so.2 nss-external.go
      - name: Run vet & lint
        run: |
          go vet .
          golint .
      - name: upload_artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nss-shim
          path: ./libnss_external.so.2
